# Generated by Django 3.1.8 on 2021-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('channel_title', models.CharField(max_length=150)),
                ('channel_id', models.CharField(max_length=100)),
            ],
        ),
    ]
